<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Calamity Reports (Combined)</title>
    <style>
        body { font-family: DejaVu Sans, Arial, sans-serif; font-size: 12px; color: #111; }
        h1 { font-size: 20px; margin: 0 0 6px; }
        h2 { font-size: 16px; margin: 12px 0 6px; }
        .muted { color: #666; }
        .section { margin-top: 12px; }
        .metrics { display: block; width: 100%; border: 1px solid #ddd; border-radius: 6px; padding: 10px; }
        .metrics-grid { display: grid; grid-template-columns: repeat(2, 1fr); gap: 8px; }
        .metric { background: #f7f7f7; padding: 8px; border-radius: 4px; }
        table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        th, td { border: 1px solid #ddd; padding: 6px; text-align: left; }
        th { background: #f0f0f0; }
        .small { font-size: 11px; }
    </style>
    <script>
        function formatDate(d) { return d; }
    </script>
</head>
<body>
    <h1>Calamity Reports</h1>
    <div class="muted small">Generated by: {{ auth()->user()->name ?? 'System' }} | Date: {{ now()->format('Y-m-d H:i') }}</div>

    <div class="section metrics">
        <h2>Summary</h2>
        <div class="metrics-grid">
            <div class="metric"><strong>Total Incidents:</strong> {{ $metrics['totalIncidents'] }}</div>
            <div class="metric"><strong>Total Affected Households:</strong> {{ $metrics['totalAffectedHouseholds'] }}</div>
            <div class="metric">
                <strong>Date Range:</strong>
                @if($metrics['dateFrom'] && $metrics['dateTo'])
                    {{ optional($metrics['dateFrom'])->format('Y-m-d') }} to {{ optional($metrics['dateTo'])->format('Y-m-d') }}
                @else
                    N/A
                @endif
            </div>
            <div class="metric">
                <strong>By Severity:</strong>
                @foreach($metrics['bySeverity'] as $sev => $count)
                    {{ ucfirst($sev) }}: {{ $count }}@if(!$loop->last), @endif
                @endforeach
            </div>
            <div class="metric"><strong>Total Affected Residents:</strong> {{ $metrics['totalAffectedResidents'] }}</div>
            <div class="metric"><strong>Families Evacuated:</strong> {{ $metrics['familiesEvacuated'] }}</div>
            <div class="metric"><strong>Total Evacuees:</strong> {{ $metrics['totalEvacuees'] }}</div>
            <div class="metric"><strong>Partially Damaged Households:</strong> {{ $metrics['partiallyDamaged'] }}</div>
            <div class="metric"><strong>Totally Damaged Households:</strong> {{ $metrics['totallyDamaged'] }}</div>
            <div class="metric"><strong>Estimated Damage Cost:</strong> ₱{{ number_format($metrics['estimatedDamageCost'], 2) }}</div>
            <div class="metric"><strong>Total Relief Distributed:</strong> {{ $metrics['totalReliefDistributed'] }}</div>
            <div class="metric"><strong>Total Rescues:</strong> {{ $metrics['totalRescues'] }}</div>
        </div>
        <div class="section">
            <strong>By Type:</strong>
            @foreach($metrics['byType'] as $type => $count)
                {{ ucfirst($type) }}: {{ $count }}@if(!$loop->last), @endif
            @endforeach
        </div>
        <div class="section">
            <strong>Relief Distributed by Item:</strong>
            @foreach($metrics['reliefByItem'] as $entry)
                {{ $entry['name'] }}: {{ $entry['quantity'] }}@if(!$loop->last), @endif
            @endforeach
        </div>
        @if($metrics['evacuationCenterOccupancy'] && count($metrics['evacuationCenterOccupancy']))
        <div class="section">
            <strong>Evacuation Center Occupancy:</strong>
            @foreach($metrics['evacuationCenterOccupancy'] as $centerId => $count)
                Center #{{ $centerId }}: {{ $count }}@if(!$loop->last), @endif
            @endforeach
        </div>
        @endif
    </div>

    <div class="section">
        <h2>Detailed Listing</h2>
        <table>
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Name</th>
                    <th>Type</th>
                    <th>Date Occurred</th>
                    <th>Severity</th>
                    <th>Reported By</th>
                    <th>Where (Affected Areas)</th>
                    <th>Status</th>
                    <th>Affected Households</th>
                </tr>
            </thead>
            <tbody>
                @foreach($calamities as $c)
                <tr>
                    <td>{{ $c->id }}</td>
                    <td>{{ $c->calamity_name ?? ucfirst($c->calamity_type) }}</td>
                    <td>{{ ucfirst($c->calamity_type) }}</td>
                    <td>{{ optional($c->date_occurred)->format('Y-m-d') }}</td>
                    <td>{{ ucfirst($c->severity_level) }}</td>
                    <td>{{ optional($c->reporter)->name ?? 'N/A' }}</td>
                    <td>{{ $c->affected_areas ?? 'N/A' }}</td>
                    <td>{{ ucfirst($c->status ?? 'n/a') }}</td>
                    <td>{{ $c->affected_households_count ?? $c->affectedHouseholds()->count() }}</td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</body>
</html>
